import Head from 'next/head'
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <div >
      <Head>
        <title>DeepSeaSider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-red-500">
        Hello
      </div>
    </div>
  )
}
